apiVersion: v1
kind: Pod
metadata:
  name: "secret-pod"
  namespace: roboshop
  labels:
    project: robohsop
  annotations:
    author: jansi
    course: devops
spec:
  containers:
    - name: "secret-c"  
      image: nginx
      volumeMounts:
        - name: mount1
          mountpath: /etc/config
  volumes:
    - name: mount1
      secret:
       secretName: secret1      
