apiVersion: v1
kind: Secret
metadata:
  name: "secret1"
  namespace: roboshop
  labels:
    project: robohsop
  annotations:
    author: jansi
    course: devops
data:
  username: "amFuc2kK"
  password: "amFuc2kyMDAxCg=="   