apiVersion: v1
kind: Secret
metadata:
  name: "secret1"
  namespace: roboshop
  labels:
    project: roboshop
  annotations:
    author: jansi
    course: devops
type: Opaque
data:
  username: "amFuc2k="
  password: "amFuc2kyMDAx"
