apiVersion: v1
kind: Pod
metadata:
  name: "volume-test"
  namespace: roboshop
  labels:
    project: roboshop
  annotations:
    author: jansi
    gmail: gorlejansi@gmail.com
spec:
  containers:

    - name: "volume-test-c1"
      image: nginx
      volumeMounts:
      - name: volume1
        mountPath: /var/logs/nginx/

    - name: "volume-test-c2"
      image: almalinux
      command: ["sleep", "10000"]
      volumeMounts:
      - name: volume1
        mountPath: /mnt/nginx-logs
        readOnly: true

  volumes:
  - name: volume1
    emptyDir:
      sizeLimit: 100Mi


# emptyDir is a temporary Pod-level volume. It is created when the Pod is scheduled to a node and exists as long as the Pod exists. Containers in the same Pod can share it. Data survives container restarts, but is deleted when the Pod is deleted or recreated.