apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    project: roboshop
    env: dev
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80

# When the Pod template in a workload resource is changed, the controller creates new Pods based on the updated template instead of updating the existing Pods.
# Individual Pods must be maintained manually. Workload resources provide self-healing, rollout updates, and replacement Pods when configuration changes.
