apiVersion: v1
kind: Pod
metadata:
  name: multi-pod-test
  namespace: roboshop
  labels:
     project: roboshop
     env: dev
spec:
  containers: 
    - name: multi-pod-test-c1  
      image: nginx
      ports:
        - containerPort: 80
    - name: multi-pod-test-c2
      image: mysql
      ports:
        - containerPort: 3306
     
