apiVersion: v1
kind: Pod
metadata: 
  name: resourcelimit-Pod
  namespace: roboshop
  labels:
    project: limit
    env: dev
  annotations:
    context: "apply limits to resources of node for a container"   
spec:
  containers:
     - name: limit-c
       image: nginx
       ports:
        - containerPort: 80
       resources:
        requests:
          cpu: "100m"
          mem: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"   

# Requests are what the container needs minimum.
# Scheduler uses requests to place Pods on nodes

# Limits are the maximum allowed to use.
# Limits protect the node from one container consuming too many resources.

# If CPU crosses the limit, Kubernetes throttles the container.
# CPU throttling = container wants more CPU, but Kubernetes allows only the limit, so app becomes slower.
# If memory crosses the limit, Kubernetes may kill the container with OOMKilled.



# kubectl get pod <pod-name> -n <namespace>
# kubectl describe pod <pod-name> -n <namespace>
# kubectl top pod <pod-name> -n <namespace>