apiVersion: v1
kind: Pod
metdata:
  name: envtest-pod
  namespace: roboshop
  labels:
    project: roboshopenv
  annotations:
    author: jansi
    gmail: jansi2001@gmail.com
    context: checking env configs 
spec:
  containers:
    - name: envtest-c  
      image: nginx
      env:
        - name: APP_ENV
          value: "dev"
        - name: APP_PORT
          value: "8080"
          
        
  env is used to pass environment variables into a container.      
  Environment variables are used to pass runtime configuration into containers, such as database host, service URLs, log level, feature flags, credentials from Secrets, config from ConfigMaps, and pod metadata. This avoids hardcoding values inside the image.
  
  