apiVersion: v1
kind: ConfigMap
metadata:
  name: "configmap-test"
  namespace: roboshop
data:
  APP_ENV: "dev"
  APP_PORT: "8080"

---
apiVersion: v1
kind: Pod
metadata:
  name: "config-map-pod"
  namespace: roboshop
  labels:
     project: roboshop
     env: dev
  annotations:
    author: jansi
    gmail: jansi2001@gmail.com
    context: runtime env configs to containers from configmaps
spec:
  containers: 
    - name: config-map-c
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: configmap-test


# configMap is used to store nonsenstive configs 
# kubectl get configmap -n <namespace>    -->all config maps
# kubectl describe configmap <name> -n <namespace>    ---> describe specific config map
# kubectl get configmap <name> -n <namespace> -o yaml --> specific config maps