apiVersion: v1
kind: Secret
metadata:
  name: "secret-test"
  namespace: roboshop
type: Opaque                    #imp base64 encoded 
data:                          #imp
  username: "amFuc2k="
  password: "amFuc2kyMDAx"

---
apiVersion: v1
kind: Pod
metadata:
  name: "secret-pod"
  namespace: roboshop
spec:
  containers:
    - name: "secret-c"
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - secretRef:                           #imp
            name: secret-test


# kubectl get secrets
# kubectl get secret <secret-name> -n <namespace>
# kubectl describe secret <secret-name> -n <namespace>




# ConfigMap/Secret data can be updated.
# Secret type cannot be changed after creation.
# Pod env values from Secret are loaded when the Pod starts.so if updated any values then delete and create again



# echo "jansi2001"| base64
# echo "jansi2001"| base64 --decode
# secrets store sensitive info like passwords,apikeys,tokens,certificates.pods can consume the secrets using environment varaibles or mounted files
# Secret values are base64 encoded in YAML, and in production we protect them using RBAC and encryption at rest.
