apiVersion: v1
kind: Secret
metadata:
  name: "secret-test"
  namespace: roboshop
type: opaque  
data:
  username: "amFuc2kK"
  password: "amFuc2kyMDAxCg=="  

---
apiVersion: v1
kind: pod
metadata:
  name: "secret-pod"
  namespace: roboshop
spec:
  containers:
    - name: "secret-c"
      image: nginx
      ports:
        - containerPort: 80
      envfrom:
        - secretRef:
            name:  secret-test   













# echo "jansi2001"| base64
# echo "jansi2001"| base64 --decode
# secrets store sensitive info like passwords,apikeys,tokens,certificates.pods can consume the secrets using environment varaibles or mounted files
# Secret values are base64 encoded in YAML, and in production we protect them using RBAC and encryption at rest.