apiVersion: v1
kind: Pod
metadata:
  name: "cluster-ip-pod"
  namespace: roboshop
  labels:
    component: frontend
    env: dev
  annotations:
    author: jansi
spec:
  containers:
    - name: "cluster-ip-c"
      image: nginx   



# when creating pod the if readiness probe are sucess then kublet will check the labels of pod and assign the pod to specific service if same  selector labels