apiVersion: v1
kind: Service
metadata:
  name: "service-nodeport"
  namespace: roboshop
spec:
  type: NodePort
  selector:
    is:  "service-nodeport-match" 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080


# Node IP:30080
#       ↓
# Service port:80
#       ↓
# Pod port:80
# opens 30080 on all nodes and to access the pod we can use any nodeip:nodeport will will call nodeportservice and kubernetes dns converts to clusterip which will call any endpoints

