apiVersion: v1
kind: Pod
metadata:
  name: "nodeport-pod"
  namespace: roboshop
  labels:
    is:  "service-nodeport-match" 
  annotations:
    author: jansi
spec:
  containers:
    - name:  "nodeport-c"
      image: nginx
      ports:
        - containerPort: 80
           

