apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: "replicaset-test"
  namespace: roboshop
  labels:
      project: roboshop
      author: jansi
spec:
  replicas: 10
  selector: 
    matchLabels:
      purpose: "replicaset-match"   # labels of pods which matches these labels are added
  template:     # pod definition
    metadata:
      labels:
        purpose: "replicaset-match"   
        name: "replicaset-pods"     
    spec:
      containers:
        - name: "replicaset-c"
          image: nginx
          ports:
            - containerPort: 80    

# kubectl apply -f 18-replicaset.yaml
# kubectl get replicasets -n roboshop
# kubectl describe replicaset <replicaset-name> -n roboshop
# kubectl get pods -n roboshop      
# kubectl get pods -n roboshop -l name=replicaset-pods
# kunbectl delete replicaset <replicaset-name> -n roboshop

# replicaset only takecare of creating pods current pods== desired replicas it will not check config or image version update