apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: "replicaset-test"
  namespace: roboshop
  labels:
      project: roboshop
      author: jansi
spec:
  replicas: 10
  selector: 
    matchLabels:
      purpose: "replicaset-match"   # labels of pods which matches these labels are added
  template:     # pod definition
    metadata:
      labels:
        purpose: "replicaset-match"   
        name: "replicaset-pods"     
    spec:
      containers:
        - name: "replicaset-c"
          image: nginx
          ports:
            - containerPort: 80    

# relicaset will only manitained desired replicas
# it will not respect any changes in config or app code 
# by default deployment will create replicaset + rolling update if any change in config/image



#  spec:
#   replicas:2
#   selector:
#     matchLabels:
#   template:
#     metadata:
#       labels:
#     spec:    
#       containers:
#         - name:
#           image:
#           ports:
#             - containerPort: