apiVersion: v1
kind: Deployment
metadata:
  name: "hpa-test"
  namespace: roboshop
  labels:
    project: "roboshop-deployment"
spec:
  replicas: 5
  selector:
    matchLabels:
      project: "hpa-Roboshop"
      env: dev
  template:
    metadata:
      name: "hpa-pod"
      namespace: roboshop
      labels:
        project: "hpa-Roboshop"
        env: dev
      annotations:
        author: "jansi"
        gmail: "gorlejansi2001@gmail.com"
    spec:
      containers:
        - name: "hpa-container"  
          image: nginx
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: "lb-hpa"
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    project: "hpa-Roboshop"
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
      nodeport: 300020             











