apiVersion: v1
kind: Pod
metadata:
  name: "test-pod"
  namespace: roboshop
spec:
  containers:
    - name: test-c
      image: busybox
      command:
        - sh
        - -c
        - |
          while true; do
              echo "" date  in container is "$( date )"  >> /data/output.log
              sleep 5
          done
      volumeMounts:
        - name: test-volume
          mountPath: /data                    # ebs volume available isnside pod here
  volumes:
    - name: test-volume
      persistentVolumeClaim:                #“Use the storage requested by TEST-PVC”
        claimName: test-pvc


