apiVersion: apps/v1
kind: Deployment
metadata:
  name: "affinity-test"
  namespace: roboshop
spec:
  replicas: 2
  selector:
    matchLabels:
      project: frontend
      env: dev  
  template:
    metadata:
      labels:
        project: frontend
        env: dev  
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:       #The node label must match.The scheduler checks the rule when placing the Pod.After the Pod starts, K8s does not evict it merely because the node label later changes.
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: capacity-type
                    operator: In
                    values:
                      - spot

            - weight: 50
              preference:
                matchExpressions:
                  - key: disktype
                    operator: In
                    values:
                      - ssd
      containers:
        - name: "affinity-c"
          image: nginx    


# All nodes
#    ↓
# Apply required affinity
#    ↓
# Remove non-Linux nodes
#    ↓
# Apply preferred affinity scores
#    ↓
# Prefer Spot and SSD nodes
#    ↓
# Check other scheduling conditions
#    ↓
# Select the best node


# operators
# In
# NotIn
# Exists
# DoesNotExist
# Gt
# Lt