apiVersion: apps/v1
kind: Deployment
metadata:
  name: "antiaffintiy-d"
  namespace: roboshop
spec:
  replicas: 2
  selector:
    matchLabels:
      project: nginx
      env: dev
  template:
    metadata:
      labels:
        project: nginx
        env: dev 
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - LabelSelector:
                matchExpressions:
                  - key: component
                    operator: In
                    values:
                      - frontend
              topologyKey: kubernetes.io/histname        
      containers:
        - name: "antiffinity-p"
          image: nginx



#pod-antiaffinity- dont keep pods with matching labels together
#scheduler checks labels of pods already running incluster and decide on which node to place