# human user/groups - use user identity to identitfy themself and get access to k8 resource  by calling k8s apiserver
# pods/applications - user serviceaccount identity to get access to k8s resources by calling k8s apiserver

# pod --> apiserver--> who is making request--> serviceaccount attached in pod identify using token,cert --->what action can you perform on which resources -->rbac check if there are bindings to this serviceaccount to role --> if yes what actions he can perform ---> can perform action send forbidden ,if can perform action send details

apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-reader
  namespace: roboshop



#  kubectl apply -f 43-serviceaccount.yaml
#  kubectl get sa  app-reader -n roboshop

# A ServiceAccount is a non-human Kubernetes identity used by Pods.
# We specify it using serviceAccountName in the Pod specification.
# Kubernetes provides the Pod with short-lived credentials that it can use to authenticate to the API server.
# A ServiceAccount alone does not provide permissions; we assign permissions through a RoleBinding or ClusterRoleBinding connected to a Role or ClusterRole. 
# We create dedicated ServiceAccounts for components such as Fluent Bit, Jenkins agents and backup jobs and grant only the minimum permissions required.