apiVersion: v1
kind: Pod
metadata:
  name: reader-pod
  namespace: roboshop
spec:
  serviceAccountName: app-reader          #Connect the ServiceAccount to a Pod; a identity is given to pod

  containers:
    - name: kubectl
      image: bitnami/kubectl
      command:
        - sh
        - -c
        - |
          kubectl get pods -n roboshop
          sleep 3600


# reader-pod runs with identity: system:serviceaccount:roboshop:app-reader
# A ServiceAccount provides an identity, but it does not automatically provide permissions.

# authentication: serviceAccount
# authorization: rbac

# ServiceAccount
#       +
# Role or ClusterRole
#       +
# RoleBinding or ClusterRoleBinding


# 1. create a serviceaccount
# 2. create a pod
# 3. attach sa to pod in spec
# 4. role to define permission 
# 5. rolebinding to bind sa to permissions