apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop-dev
  region: us-east-1

iam:
  withOIDC: true

managedNodeGroups:
  - name: roboshop-dev-ng
    instanceType: t3.medium
    minSize: 0
    desiredCapacity: 2
    maxSize: 2
    volumeSize: 20
    labels:
      role: daily-lab
    tags:
      project: roboshop
      purpose: eks-daily-practice
      lifecycle: temporary
