apiVersion: v1      #headless service
kind: Service
metadata:
  name: "statefulset-headless-service"
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    author: jansi
    project: "roboshop-statefulset-test" 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1    #cluster-ip service
kind: Service
metadata:
  name: "statefulset-clusterip-service"
  namespace: roboshop
spec:
  selector:
    author: jansi
    project: "roboshop-statefulset-test" 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "statefulset-test"
  namespace: roboshop
  labels:
    project: "roboshop-statefulset-test"
spec:
  replicas: 3
  serviceName: statefulset-headless-service       # mention headless service 
  selector:
    matchLabels:
      author: jansi
      project: "roboshop-statefulset-test"
  template:
    metadata:
      labels:
        author: jansi
        project: "roboshop-statefulset-test"
    spec:
      containers:
        - name: "roboshop-statefulset-container"
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: stateful-volume
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:       # Create a separate PVC for every StatefulSet Pod.
    - metadata: 
        name: stateful-volume
      spec:
        accessModes: 
          - ReadWriteOnce
        storageClassName: "ebs-storageclass"
        resources:
          requests:
            storage: 1Gi

      # volumes:
      #   - name: stateful volume
      #     persistentVolumeClaim:
      #       claimName: <name>         









# stateful set should have pvc,clusterip-service,headless service
# kubectl get svc -n roboshop
# kubectl get statefulset -n roboshop
# kubectl get pods -n roboshop -l project=roboshop-statefulset-test -o wide
# kubectl get pv -n roboshop -o wide
# kubectl get pvc -n roboshop -o wide
# kubectl scale statefulset <name> --replicas = 5