apiVersion: v1
kind: Service
metadata:
  name: "headless-service"
  namespace: roboshop
  labels:
    project: "headless-service-roboshop"
    env: dev
spec:
  clusterIP: none
  selector: 
    author: jansi
    project: "headless-service-roboshop"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: "headless-pod-1"
  labels:
    author: jansi
    project: "headless-service-roboshop"
spec:
  containers:
    - name: "headless-pod-c"
      image: nginx
      ports:
        - containerPorts: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: "headless-pod-2"
  labels:
    author: jansi
    project: "headless-service-roboshop"
spec:
  containers:
    - name: "headless-pod-c"
      image: nginx
      ports:
        - containerPorts: 80
        

