apiVersion: apps/v1
kind: Depolyment
metadata:
  name: test-deploy
  namespace: roboshop
spec:
  replicas: 2
  selector: 
    matchLables:
      app: roboshop
      component: test
  template:
    metadata:
      labels:
        app: roboshop
        component: test
    spec:
      volumes:
        - name: volume1
          emptyDir: {}  
      initContainers:
        - name: create-homepage
          image: busybox:1.36
          command:
            - sh
            - c
            - |
              echo "<h1>Welcome to RoboShop.. Jansi...!</h1>" > /data/index.html
          volumeMounts:
            - name: volume1
              mountPath: /data
      containers: 
        - name: test-container
          image: nginx
          volumeMounts:
            - name: volume1
              mountPath: /usr/share/nginx/html
        


