apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/part-of: kubernetes-centralized-logging
    project: central-logging





# Provides Pod identity and serviceaccount token , while allowing traffic from apiserver to inside 


# Fluent Bit:
# “I need information about the cart Pod.”

# API Server:
# “Who are you?”

# Fluent Bit:
# “I am the fluent-bit ServiceAccount.”

# API Server:
# “Let me check your RBAC permissions.”


# ServiceAccount → identity
# ClusterRole    → permissions
# RoleBinding    → connects identity to permissions